### ISSUE TITLE
IP requirement

### ISSUE THREAD

**Issue by ghost** [The-Taggart-Institute/kasm-manager#2]
Hi, i got this issue:

How to know what ip to input?
When in the readme there is written that "To set up worker nodes, make sure that the correct IPs  are listed in the Ansible/inventory.yml file."

also, in the said config file:

```kasm-workers:
  children:
    managers:
      hosts:
        10.0.2.4:
    workers:
      hosts:
        10.0.2.6:
        10.0.2.5:
```
Are we supposed to change the ip as itself or add an ip after the ":".        
I assume the manager host ip should be the one exposed, but the workers, should i be some free docker ip or from the internal system  like 192.168.10.1.

Thanks for your help ;D

**Comment by mttaggart** [comment]
Yeah, you need to modify this to match your deployment. Whatever your manager IP is, put that in the `managers.hosts` section. Same with all your workers.
